#!/usr/bin/env python3
"""Work out what a calibration G-code actually contains.

Point it at files or a directory (e.g. an SD card) and it reports, per file:
what printer/filament/process made it, which calibration test it looks like,
and the parameter the test sweeps -- the temperatures a temp tower steps
through, the retraction lengths a retraction tower tries, and so on.

    python3 scripts/inspect_gcode.py /media/$USER/SDCARD
    python3 scripts/inspect_gcode.py foo.gcode bar.gcode
"""
import os
import re
import sys

CONFIG_KEYS = [
    "printer_settings_id", "filament_settings_id", "print_settings_id",
    "filament_type", "nozzle_temperature", "hot_plate_temp",
    "filament_max_volumetric_speed", "filament_flow_ratio",
    "retraction_length", "filament_retraction_length", "retraction_speed",
    "layer_height", "sparse_infill_density", "wall_loops",
    "z_hop", "z_hop_types", "wipe",
]


def read(path):
    with open(path, "rb") as fh:
        return fh.read().decode("utf-8", errors="replace")


def config_block(text):
    out = {}
    for m in re.finditer(r"^;\s*([a-z0-9_]+)\s*=\s*(.*)$", text, re.M):
        k, v = m.group(1), m.group(2).strip()
        if k in CONFIG_KEYS and v and not out.get(k):
            out[k] = v          # keep the first NON-EMPTY value, not the first
    return out


def temp_sweep(text):
    """Nozzle temperature changes during printing, with the Z they happen at.

    Ignores anything before the first extrusion and after the last: the start
    G-code preheat and the end G-code M104 S0 otherwise look like a two-step
    "sweep" and every normal print gets misread as a temperature tower.
    """
    lines = text.splitlines()
    extruding = [i for i, l in enumerate(lines)
                 if l.startswith(("G1 ", "G0 ")) and re.search(r"\bE-?[0-9.]", l)]
    if not extruding:
        return []
    first, last = extruding[0], extruding[-1]

    events, z = [], None
    for i, line in enumerate(lines):
        if line.startswith(("G1 ", "G0 ")):
            m = re.search(r"\bZ([0-9.]+)", line)
            if m:
                z = float(m.group(1))
        elif first <= i <= last and line.startswith(("M104", "M109")):
            m = re.search(r"\bS([0-9]+)", line)
            if m:
                t = int(m.group(1))
                if t > 0 and (not events or events[-1][1] != t):
                    events.append((z, t))
    return events


def retraction_lengths(text):
    vals = {}
    for m in re.finditer(r"^G1 (?:F[0-9.]+ )?E-([0-9.]+)\s*$", text, re.M):
        v = round(float(m.group(1)), 3)
        vals[v] = vals.get(v, 0) + 1
    return sorted(vals.items(), key=lambda kv: -kv[1])


def guess_test(text, cfg, temps, filename=""):
    name = ""
    m = re.search(r"^;\s*(?:plate name|model label id)\s*[:=]\s*(.+)$", text, re.M)
    if m:
        name = m.group(1).strip().lower()
    # Filename and plate name only -- never the config block, whose setting
    # names contain words like "volumetric" and would match everything.
    blob = (os.path.basename(filename) + " " + name).lower()
    for key, label in [
        ("tolerance", "Tolerance test"),
        ("stringhell", "Stringing test (stringhell)"),
        ("volumetric", "Max volumetric speed / max flowrate"),
        ("flowrate", "Flow rate calibration"),
        ("flow rate", "Flow rate calibration"),
        ("pressure", "Pressure advance"),
        ("retraction", "Retraction tower"),
        ("temperature", "Temperature tower"),
        ("ringing", "Input shaping / ringing tower"),
        ("vfa", "VFA test"),
    ]:
        if key in blob:
            return label
    if len({t for _, t in temps}) >= 3:
        return "Temperature tower (inferred: multiple nozzle temps)"
    return "unknown / normal print"


def human_time(text):
    m = re.search(r"model printing time:\s*([^;]+);\s*total estimated time:\s*(.+)", text)
    if m:
        return m.group(2).strip()
    m = re.search(r"estimated printing time \(normal mode\)\s*=\s*(.+)", text)
    return m.group(1).strip() if m else "?"


def inspect(path):
    text = read(path)
    cfg = config_block(text)
    temps = temp_sweep(text)
    print(f"\n══ {os.path.basename(path)}   ({os.path.getsize(path)/1e6:.1f} MB)")
    print(f"   test        : {guess_test(text, cfg, temps, path)}")
    gen = re.search(r"^;\s*(generated by .+|BambuStudio .+)$", text, re.M)
    if gen:
        print(f"   slicer      : {gen.group(1).strip()}")
    for k in ("printer_settings_id", "filament_settings_id", "print_settings_id"):
        if cfg.get(k):
            print(f"   {k.replace('_settings_id',''):<12}: {cfg[k]}")
    print(f"   est. time   : {human_time(text)}")

    uniq = []
    for _, t in temps:
        if not uniq or uniq[-1] != t:
            uniq.append(t)
    if len(set(uniq)) > 1:
        print(f"   TEMP SWEEP  : {' → '.join(str(t) for t in uniq)} °C")
        bands = [(z, t) for z, t in temps if z is not None]
        if bands:
            print("   band starts :", ", ".join(f"{t}°C@Z{z:.1f}" for z, t in bands[:12]))
    elif uniq:
        print(f"   nozzle temp : {uniq[0]} °C (constant)")

    rl = retraction_lengths(text)
    if rl:
        shown = ", ".join(f"{v} mm ×{n}" for v, n in rl[:6])
        print(f"   retractions : {shown}")
        if len(rl) > 3:
            print("                 (many distinct values → likely a retraction tower)")

    for k in ("filament_max_volumetric_speed", "filament_flow_ratio",
              "layer_height", "sparse_infill_density", "wall_loops", "z_hop_types"):
        if cfg.get(k):
            print(f"   {k:<28}: {cfg[k]}")


def main(argv):
    paths = []
    for a in argv:
        if os.path.isdir(a):
            for root, _, files in os.walk(a):
                for f in sorted(files):
                    if f.lower().endswith((".gcode", ".gco", ".g")):
                        paths.append(os.path.join(root, f))
        elif os.path.isfile(a):
            paths.append(a)
    if not paths:
        print("no g-code found in: " + ", ".join(argv), file=sys.stderr)
        return 1
    for p in paths:
        try:
            inspect(p)
        except Exception as exc:
            print(f"\n══ {os.path.basename(p)}\n   ERROR: {exc}")
    print()
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
