#!/usr/bin/env python3
"""Read time/filament estimates out of sliced G-code headers.

Three formats are in play and they do not agree on key names, and one lies
about its units:

  Orca + Marlin (Ender 3 Pro)
      ; filament used [mm] = 1285.80
      ; filament used [cm3] = 3.09
      ; total filament used [g] = 3.74
      ; estimated printing time (normal mode) = 36m 7s

  Orca + BBL flavour (H2S)
      ; filament used [g] = 3.56              <- no "total"
      ; model printing time: 20m 37s; total estimated time: 26m 22s

  Bambu Studio (H2S)
      ; total filament length [mm] : 1201.65
      ; total filament volume [cm^3] : 2890.32   <- actually mm^3, mislabelled
      ; total filament weight [g] : 3.50

Missing fields are reported as MISSING. Nothing is interpolated or guessed.
"""
import csv
import os
import re
import sys

MISSING = "MISSING"


def _num(text):
    m = re.search(r"[-+]?\d*\.?\d+", text)
    return float(m.group()) if m else None


def parse_duration(text):
    """'1d 2h 36m 7s' -> seconds."""
    if not text:
        return None
    total, found = 0, False
    for value, unit in re.findall(r"(\d+\.?\d*)\s*([dhms])", text):
        total += float(value) * {"d": 86400, "h": 3600, "m": 60, "s": 1}[unit]
        found = True
    return total if found else None


def human(seconds):
    if seconds is None:
        return MISSING
    seconds = int(round(seconds))
    d, rem = divmod(seconds, 86400)
    h, rem = divmod(rem, 3600)
    m, s = divmod(rem, 60)
    parts = []
    if d:
        parts.append(f"{d}d")
    if h or d:
        parts.append(f"{h}h")
    parts.append(f"{m}m")
    if not d and not h:
        parts.append(f"{s}s")
    return " ".join(parts)


def parse_gcode(path, head_lines=400, tail_bytes=200_000):
    """Scan the header and the trailing summary block only — G-code bodies are huge."""
    chunks = []
    with open(path, "rb") as fh:
        for _ in range(head_lines):
            line = fh.readline()
            if not line:
                break
            chunks.append(line)
        head = b"".join(chunks)
        size = os.path.getsize(path)
        fh.seek(max(0, size - tail_bytes))
        tail = fh.read()
    text = (head + b"\n" + tail).decode("utf-8", errors="replace")

    out = {
        "slicer_version": MISSING,
        "time_model_s": None,
        "time_total_s": None,
        "filament_mm": None,
        "filament_cm3": None,
        "filament_g": None,
    }

    for line in text.splitlines():
        if not line.startswith(";"):
            continue
        low = line.lower()

        if "generated by orcaslicer" in low:
            m = re.search(r"orcaslicer\s+(\S+)", low)
            if m:
                out["slicer_version"] = f"OrcaSlicer {m.group(1)}"
        elif low.startswith("; bambustudio "):
            out["slicer_version"] = f"BambuStudio {line.split()[2]}"

        # --- time ---
        if "model printing time:" in low:
            m = re.search(r"model printing time:\s*([^;]+)", line, re.I)
            if m:
                out["time_model_s"] = parse_duration(m.group(1))
            m = re.search(r"total estimated time:\s*(.+)", line, re.I)
            if m:
                out["time_total_s"] = parse_duration(m.group(1))
        elif "estimated printing time (normal mode)" in low and "first layer" not in low:
            out["time_total_s"] = parse_duration(line.split("=", 1)[-1])

        # --- filament ---
        elif "total filament length [mm]" in low:
            out["filament_mm"] = _num(line.split(":", 1)[-1])
        elif "filament used [mm]" in low:
            out["filament_mm"] = _num(line.split("=", 1)[-1])
        elif "total filament volume" in low:
            # Bambu Studio labels this cm^3 but emits mm^3.
            v = _num(line.split(":", 1)[-1])
            out["filament_cm3"] = v / 1000.0 if v is not None else None
        elif "filament used [cm3]" in low:
            out["filament_cm3"] = _num(line.split("=", 1)[-1])
        elif "total filament weight [g]" in low:
            out["filament_g"] = _num(line.split(":", 1)[-1])
        elif re.search(r";\s*(total )?filament used \[g\]", low):
            out["filament_g"] = _num(line.split("=", 1)[-1])

    if out["time_total_s"] is None:
        out["time_total_s"] = out["time_model_s"]
    return out


def collect(out_root):
    rows = []
    for dirpath, _, files in os.walk(out_root):
        for f in sorted(files):
            if not f.endswith(".gcode"):
                continue
            path = os.path.join(dirpath, f)
            rel = os.path.relpath(path, out_root)
            parts = rel.split(os.sep)
            if parts[0] == "preflight":
                # The squish coupon is a normal complete slice and its header is
                # accurate, so it belongs in the table. The adhesion checks are
                # truncated copies whose headers still describe the FULL print,
                # so listing them would report 11h for a 1h job. preflight.py
                # stamps them, which is how we tell the two apart.
                # The stamp sits near the END, just before the end g-code.
                with open(path, "rb") as fh:
                    fh.seek(max(0, os.path.getsize(path) - 200_000))
                    if b"pre-flight truncation" in fh.read():
                        continue
            if parts[0] == "preflight":
                # out/preflight/<printer>_squish_coupon.gcode
                stem = os.path.splitext(parts[-1])[0]
                printer, _, _ = stem.partition("_")
                kind = "squish"
            else:
                printer = parts[0] if parts else "?"
                kind = parts[1] if len(parts) > 1 else "?"
            slicer = "bambustudio" if "bambustudio" in parts else "orca"

            d = parse_gcode(path)
            g = d["filament_g"]
            rows.append(
                {
                    "printer": printer,
                    "slicer": slicer,
                    "kind": kind,
                    "job": os.path.splitext(os.path.basename(rel))[0],
                    "time": human(d["time_total_s"]),
                    "time_s": int(d["time_total_s"]) if d["time_total_s"] is not None else MISSING,
                    "filament_g": f"{g:.2f}" if g is not None else MISSING,
                    "filament_mm": f"{d['filament_mm']:.1f}" if d["filament_mm"] is not None else MISSING,
                    "filament_cm3": f"{d['filament_cm3']:.2f}" if d["filament_cm3"] is not None else MISSING,
                    "slicer_version": d["slicer_version"],
                    "gcode": rel,
                }
            )
    rows.sort(key=lambda r: (r["printer"], r["kind"], r["slicer"], r["job"]))
    return rows


FIELDS = [
    "printer", "slicer", "kind", "job", "time", "time_s",
    "filament_g", "filament_mm", "filament_cm3", "slicer_version", "gcode",
]


def write_csv(rows, path):
    with open(path, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=FIELDS)
        w.writeheader()
        w.writerows(rows)


def write_md(rows, path):
    lines = [
        "# TPU slice estimates",
        "",
        "CC3D TPU 98A Skin · generated by `scripts/parse_estimates.py`",
        "",
        "> Estimates are only as good as the filament profile. While the profile still",
        "> says PENDING, treat these as **relative** numbers for comparing printers,",
        "> not as absolute print times.",
        "",
    ]
    if not rows:
        lines += ["_No G-code found. Run `./run.sh` first._", ""]
    else:
        head = ["Printer", "Slicer", "Kind", "Job", "Est. time", "Filament (g)", "(mm)", "(cm³)"]
        lines.append("| " + " | ".join(head) + " |")
        lines.append("|" + "|".join(["---"] * len(head)) + "|")
        for r in rows:
            lines.append(
                "| {printer} | {slicer} | {kind} | `{job}` | {time} | {filament_g} | "
                "{filament_mm} | {filament_cm3} |".format(**r)
            )
        lines.append("")

        # Same job on both printers -> head-to-head.
        by_job = {}
        for r in rows:
            by_job.setdefault((r["kind"], r["job"]), []).append(r)
        cross = {k: v for k, v in by_job.items() if len({x["printer"] for x in v}) > 1}
        if cross:
            lines += ["## Head to head", ""]
            for (kind, job), group in sorted(cross.items()):
                lines.append(f"**{job}** ({kind})")
                lines.append("")
                for r in sorted(group, key=lambda x: (x["printer"], x["slicer"])):
                    lines.append(
                        f"- {r['printer']} / {r['slicer']}: {r['time']}, {r['filament_g']} g"
                    )
                lines.append("")

        n_missing = sum(1 for r in rows for k in ("time", "filament_g") if r[k] == MISSING)
        if n_missing:
            lines += [f"> {n_missing} field(s) reported MISSING — the slicer did not emit them.", ""]

    with open(path, "w") as fh:
        fh.write("\n".join(lines))


def main(argv):
    out_root = argv[0] if argv else "out"
    rows = collect(out_root)
    write_csv(rows, os.path.join(out_root, "estimates.csv"))
    write_md(rows, os.path.join(out_root, "estimates.md"))
    print(f"parsed {len(rows)} g-code file(s)")
    print(f"  {out_root}/estimates.csv")
    print(f"  {out_root}/estimates.md")
    for r in rows:
        print(f"  {r['printer']:<10} {r['slicer']:<12} {r['kind']:<12} "
              f"{r['job'][:32]:<32} {r['time']:>10}  {r['filament_g']:>8} g")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
